/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 06/04/2022 13:34:04
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                84000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  192000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- CAN1       --------------------------------*/

#define MX_CAN1                                 1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_CAN1_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Pin                          PA11
#define MX_CAN1_RX_GPIOx                        GPIOA
#define MX_CAN1_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_RX_GPIO_Pin                     GPIO_PIN_11
#define MX_CAN1_RX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_CAN1_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Pin                          PA12
#define MX_CAN1_TX_GPIOx                        GPIOA
#define MX_CAN1_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_TX_GPIO_Pin                     GPIO_PIN_12
#define MX_CAN1_TX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC CAN1_RX0_IRQn */
#define MX_CAN1_RX0_IRQn_interruptPremptionPriority 4
#define MX_CAN1_RX0_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_3
#define MX_CAN1_RX0_IRQn_Subriority             0

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PB11 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SDA_Pin                         PB11
#define MX_I2C2_SDA_GPIOx                       GPIOB
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_11
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB10 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C2_SCL_Pin                         PB10
#define MX_I2C2_SCL_GPIOx                       GPIOB
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_10
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C3       --------------------------------*/

#define MX_I2C3                                 1

/* GPIO Configuration */

/* Pin PC9 */
#define MX_I2C3_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C3_SDA_Pin                         PC9
#define MX_I2C3_SDA_GPIOx                       GPIOC
#define MX_I2C3_SDA_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C3_SDA_GPIO_AF                     GPIO_AF4_I2C3
#define MX_I2C3_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C3_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PA8 */
#define MX_I2C3_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C3_SCL_Pin                         PA8
#define MX_I2C3_SCL_GPIOx                       GPIOA
#define MX_I2C3_SCL_GPIO_Pin                    GPIO_PIN_8
#define MX_I2C3_SCL_GPIO_AF                     GPIO_AF4_I2C3
#define MX_I2C3_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C3_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SPI3       --------------------------------*/

#define MX_SPI3                                 1

/* GPIO Configuration */

/* Pin PC10 */
#define MX_SPI3_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_SCK_Pin                         PC10
#define MX_SPI3_SCK_GPIOx                       GPIOC
#define MX_SPI3_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI3_SCK_GPIO_Pin                    GPIO_PIN_10
#define MX_SPI3_SCK_GPIO_AF                     GPIO_AF6_SPI3
#define MX_SPI3_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_SPI3_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_MISO_Pin                        PC11
#define MX_SPI3_MISO_GPIOx                      GPIOC
#define MX_SPI3_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI3_MISO_GPIO_Pin                   GPIO_PIN_11
#define MX_SPI3_MISO_GPIO_AF                    GPIO_AF6_SPI3
#define MX_SPI3_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_SPI3_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI3_MOSI_Pin                        PC12
#define MX_SPI3_MOSI_GPIOx                      GPIOC
#define MX_SPI3_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI3_MOSI_GPIO_Pin                   GPIO_PIN_12
#define MX_SPI3_MOSI_GPIO_AF                    GPIO_AF6_SPI3
#define MX_SPI3_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_HIGH
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PA10 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_HIGH
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/* NVIC Configuration */

/* NVIC USART1_IRQn */
#define MX_USART1_IRQn_interruptPremptionPriority 3
#define MX_USART1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_3
#define MX_USART1_IRQn_Subriority               1

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2

/* Pin PA3 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 3
#define MX_USART2_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_3
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PF9 */
#define MX_PF9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF9_Pin                              PF9
#define MX_PF9_GPIOx                            GPIOF
#define MX_PF9_PinState                         GPIO_PIN_SET
#define MX_PF9_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED4                                 PF9
#define MX_PF9_GPIO_Pin                         GPIO_PIN_9
#define MX_PF9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PF8 */
#define MX_PF8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF8_Pin                              PF8
#define MX_PF8_GPIOx                            GPIOF
#define MX_PF8_PinState                         GPIO_PIN_SET
#define MX_PF8_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED3                                 PF8
#define MX_PF8_GPIO_Pin                         GPIO_PIN_8
#define MX_PF8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PB9 */
#define MX_PB9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB9_Pin                              PB9
#define MX_PB9_GPIOx                            GPIOB
#define MX_PB9_PinState                         GPIO_PIN_RESET
#define MX_PB9_GPIO_PuPd                        GPIO_NOPULL
#define MX_V24V_OUT1                            PB9
#define MX_PB9_GPIO_Pin                         GPIO_PIN_9
#define MX_PB9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB8 */
#define MX_PB8_Pin                              PB8
#define MX_PB8_GPIOx                            GPIOB
#define MX_PB8_GPIO_PuPd                        GPIO_NOPULL
#define MX_POWERON_REMOTEIN                     PB8
#define MX_PB8_GPIO_Pin                         GPIO_PIN_8
#define MX_PB8_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PG2 */
#define MX_PG2_Pin                              PG2
#define MX_PG2_GPIOx                            GPIOG
#define MX_PG2_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_IN_19                             PG2
#define MX_PG2_GPIO_Pin                         GPIO_PIN_2
#define MX_PG2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PG1 */
#define MX_PG1_Pin                              PG1
#define MX_PG1_GPIOx                            GPIOG
#define MX_PG1_GPIO_PuPd                        GPIO_NOPULL
#define MX_ACPower_OK                           PG1
#define MX_PG1_GPIO_Pin                         GPIO_PIN_1
#define MX_PG1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PG4 */
#define MX_PG4_GPIO_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_PG4_Pin                              PG4
#define MX_PG4_GPIOx                            GPIOG
#define MX_PG4_PinState                         GPIO_PIN_SET
#define MX_PG4_GPIO_PuPd                        GPIO_PULLUP
#define MX_LAN9252_CS                           PG4
#define MX_PG4_GPIO_Pin                         GPIO_PIN_4
#define MX_PG4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG3 */
#define MX_PG3_Pin                              PG3
#define MX_PG3_GPIOx                            GPIOG
#define MX_PG3_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_IN_18                             PG3
#define MX_PG3_GPIO_Pin                         GPIO_PIN_3
#define MX_PG3_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PG6 */
#define MX_PG6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG6_Pin                              PG6
#define MX_PG6_GPIOx                            GPIOG
#define MX_PG6_PinState                         GPIO_PIN_SET
#define MX_PG6_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_OUT_4                             PG6
#define MX_PG6_GPIO_Pin                         GPIO_PIN_6
#define MX_PG6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PG5 */
#define MX_PG5_Pin                              PG5
#define MX_PG5_GPIOx                            GPIOG
#define MX_PG5_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_IN_17                             PG5
#define MX_PG5_GPIO_Pin                         GPIO_PIN_5
#define MX_PG5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PC4 */
#define MX_PC4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC4_Pin                              PC4
#define MX_PC4_GPIOx                            GPIOC
#define MX_PC4_PinState                         GPIO_PIN_SET
#define MX_PC4_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED2                                 PC4
#define MX_PC4_GPIO_Pin                         GPIO_PIN_4
#define MX_PC4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PG8 */
#define MX_PG8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG8_Pin                              PG8
#define MX_PG8_GPIOx                            GPIOG
#define MX_PG8_PinState                         GPIO_PIN_SET
#define MX_PG8_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_OUT_2                             PG8
#define MX_PG8_GPIO_Pin                         GPIO_PIN_8
#define MX_PG8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PG7 */
#define MX_PG7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG7_Pin                              PG7
#define MX_PG7_GPIOx                            GPIOG
#define MX_PG7_PinState                         GPIO_PIN_SET
#define MX_PG7_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_OUT_3                             PG7
#define MX_PG7_GPIO_Pin                         GPIO_PIN_7
#define MX_PG7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PC5 */
#define MX_PC5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC5_Pin                              PC5
#define MX_PC5_GPIOx                            GPIOC
#define MX_PC5_PinState                         GPIO_PIN_SET
#define MX_PC5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED1                                 PC5
#define MX_PC5_GPIO_Pin                         GPIO_PIN_5
#define MX_PC5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PG9 */
#define MX_PG9_Pin                              PG9
#define MX_PG9_GPIOx                            GPIOG
#define MX_PG9_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_IN_6                              PG9
#define MX_PG9_GPIO_Pin                         GPIO_PIN_9
#define MX_PG9_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PC8 */
#define MX_PC8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC8_Pin                              PC8
#define MX_PC8_GPIOx                            GPIOC
#define MX_PC8_PinState                         GPIO_PIN_SET
#define MX_PC8_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_OUT_1                             PC8
#define MX_PC8_GPIO_Pin                         GPIO_PIN_8
#define MX_PC8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PF10 */
#define MX_PF10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF10_Pin                             PF10
#define MX_PF10_GPIOx                           GPIOF
#define MX_PF10_PinState                        GPIO_PIN_SET
#define MX_PF10_GPIO_PuPd                       GPIO_NOPULL
#define MX_LED5                                 PF10
#define MX_PF10_GPIO_Pin                        GPIO_PIN_10
#define MX_PF10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PB14 */
#define MX_PB14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB14_Pin                             PB14
#define MX_PB14_GPIOx                           GPIOB
#define MX_PB14_PinState                        GPIO_PIN_SET
#define MX_PB14_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_17                            PB14
#define MX_PB14_GPIO_Pin                        GPIO_PIN_14
#define MX_PB14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PD12 */
#define MX_PD12_Pin                             PD12
#define MX_PD12_GPIOx                           GPIOD
#define MX_PD12_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_22                             PD12
#define MX_PD12_GPIO_Pin                        GPIO_PIN_12
#define MX_PD12_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PB13 */
#define MX_PB13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB13_Pin                             PB13
#define MX_PB13_GPIOx                           GPIOB
#define MX_PB13_PinState                        GPIO_PIN_SET
#define MX_PB13_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_18                            PB13
#define MX_PB13_GPIO_Pin                        GPIO_PIN_13
#define MX_PB13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PD11 */
#define MX_PD11_Pin                             PD11
#define MX_PD11_GPIOx                           GPIOD
#define MX_PD11_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_23                             PD11
#define MX_PD11_GPIO_Pin                        GPIO_PIN_11
#define MX_PD11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF12 */
#define MX_PF12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF12_Pin                             PF12
#define MX_PF12_GPIOx                           GPIOF
#define MX_PF12_PinState                        GPIO_PIN_RESET
#define MX_PF12_GPIO_PuPd                       GPIO_NOPULL
#define MX_POWER24V_ON                          PF12
#define MX_PF12_GPIO_Pin                        GPIO_PIN_12
#define MX_PF12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD14 */
#define MX_PD14_Pin                             PD14
#define MX_PD14_GPIOx                           GPIOD
#define MX_PD14_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_24                             PD14
#define MX_PD14_GPIO_Pin                        GPIO_PIN_14
#define MX_PD14_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF11 */
#define MX_PF11_Pin                             PF11
#define MX_PF11_GPIOx                           GPIOF
#define MX_PF11_GPIO_PuPd                       GPIO_NOPULL
#define MX_SAFE_48V_SWITCH                      PF11
#define MX_PF11_GPIO_Pin                        GPIO_PIN_11
#define MX_PF11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PB15 */
#define MX_PB15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB15_Pin                             PB15
#define MX_PB15_GPIOx                           GPIOB
#define MX_PB15_PinState                        GPIO_PIN_SET
#define MX_PB15_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_8                             PB15
#define MX_PB15_GPIO_Pin                        GPIO_PIN_15
#define MX_PB15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PD13 */
#define MX_PD13_Pin                             PD13
#define MX_PD13_GPIOx                           GPIOD
#define MX_PD13_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_21                             PD13
#define MX_PD13_GPIO_Pin                        GPIO_PIN_13
#define MX_PD13_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PB12 */
#define MX_PB12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB12_Pin                             PB12
#define MX_PB12_GPIOx                           GPIOB
#define MX_PB12_PinState                        GPIO_PIN_SET
#define MX_PB12_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_19                            PB12
#define MX_PB12_GPIO_Pin                        GPIO_PIN_12
#define MX_PB12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PD10 */
#define MX_PD10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD10_Pin                             PD10
#define MX_PD10_GPIOx                           GPIOD
#define MX_PD10_PinState                        GPIO_PIN_SET
#define MX_PD10_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_5                             PD10
#define MX_PD10_GPIO_Pin                        GPIO_PIN_10
#define MX_PD10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PF13 */
#define MX_PF13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF13_Pin                             PF13
#define MX_PF13_GPIOx                           GPIOF
#define MX_PF13_PinState                        GPIO_PIN_SET
#define MX_PF13_GPIO_PuPd                       GPIO_NOPULL
#define MX_ES_SHUTDOWN                          PF13
#define MX_PF13_GPIO_Pin                        GPIO_PIN_13
#define MX_PF13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD15 */
#define MX_PD15_Pin                             PD15
#define MX_PD15_GPIOx                           GPIOD
#define MX_PD15_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_20                             PD15
#define MX_PD15_GPIO_Pin                        GPIO_PIN_15
#define MX_PD15_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PD7 */
#define MX_PD7_Pin                              PD7
#define MX_PD7_GPIOx                            GPIOD
#define MX_PD7_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_IN_7                              PD7
#define MX_PD7_GPIO_Pin                         GPIO_PIN_7
#define MX_PD7_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD6 */
#define MX_PD6_Pin                              PD6
#define MX_PD6_GPIOx                            GPIOD
#define MX_PD6_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_IN_8                              PD6
#define MX_PD6_GPIO_Pin                         GPIO_PIN_6
#define MX_PD6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD9 */
#define MX_PD9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD9_Pin                              PD9
#define MX_PD9_GPIOx                            GPIOD
#define MX_PD9_PinState                         GPIO_PIN_SET
#define MX_PD9_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_OUT_6                             PD9
#define MX_PD9_GPIO_Pin                         GPIO_PIN_9
#define MX_PD9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PD8 */
#define MX_PD8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD8_Pin                              PD8
#define MX_PD8_GPIOx                            GPIOD
#define MX_PD8_PinState                         GPIO_PIN_SET
#define MX_PD8_GPIO_PuPd                        GPIO_NOPULL
#define MX_ST_OUT_7                             PD8
#define MX_PD8_GPIO_Pin                         GPIO_PIN_8
#define MX_PD8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PE0 */
#define MX_PE0_Pin                              PE0
#define MX_PE0_GPIOx                            GPIOE
#define MX_PE0_GPIO_PuPd                        GPIO_NOPULL
#define MX_POWERON_KEYIN                        PE0
#define MX_PE0_GPIO_Pin                         GPIO_PIN_0
#define MX_PE0_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PE2 */
#define MX_PE2_Pin                              PE2
#define MX_PE2_GPIOx                            GPIOE
#define MX_PE2_GPIO_PuPd                        GPIO_NOPULL
#define MX_SYNC0                                PE2
#define MX_PE2_GPIO_Pin                         GPIO_PIN_2
#define MX_PE2_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_FALLING

/* Pin PE1 */
#define MX_PE1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE1_Pin                              PE1
#define MX_PE1_GPIOx                            GPIOE
#define MX_PE1_PinState                         GPIO_PIN_RESET
#define MX_PE1_GPIO_PuPd                        GPIO_NOPULL
#define MX_OC_PROTECT                           PE1
#define MX_PE1_GPIO_Pin                         GPIO_PIN_1
#define MX_PE1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE3 */
#define MX_PE3_Pin                              PE3
#define MX_PE3_GPIOx                            GPIOE
#define MX_PE3_GPIO_PuPd                        GPIO_NOPULL
#define MX_SYNC1                                PE3
#define MX_PE3_GPIO_Pin                         GPIO_PIN_3
#define MX_PE3_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_FALLING

/* Pin PE6 */
#define MX_PE6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE6_Pin                              PE6
#define MX_PE6_GPIOx                            GPIOE
#define MX_PE6_PinState                         GPIO_PIN_RESET
#define MX_PE6_GPIO_PuPd                        GPIO_NOPULL
#define MX_AI_IU_SW1                            PE6
#define MX_PE6_GPIO_Pin                         GPIO_PIN_6
#define MX_PE6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA1 */
#define MX_PA1_Pin                              PA1
#define MX_PA1_GPIOx                            GPIOA
#define MX_PA1_GPIO_PuPd                        GPIO_NOPULL
#define MX_IRQ                                  PA1
#define MX_PA1_GPIO_Pin                         GPIO_PIN_1
#define MX_PA1_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_FALLING

/* Pin PA4 */
#define MX_PA4_GPIO_Speed                       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_PA4_Pin                              PA4
#define MX_PA4_GPIOx                            GPIOA
#define MX_PA4_PinState                         GPIO_PIN_SET
#define MX_PA4_GPIO_PuPd                        GPIO_PULLUP
#define MX_RS485_RE                             PA4
#define MX_PA4_GPIO_Pin                         GPIO_PIN_4
#define MX_PA4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE11 */
#define MX_PE11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE11_Pin                             PE11
#define MX_PE11_GPIOx                           GPIOE
#define MX_PE11_PinState                        GPIO_PIN_SET
#define MX_PE11_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_23                            PE11
#define MX_PE11_GPIO_Pin                        GPIO_PIN_11
#define MX_PE11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PE10 */
#define MX_PE10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE10_Pin                             PE10
#define MX_PE10_GPIOx                           GPIOE
#define MX_PE10_PinState                        GPIO_PIN_SET
#define MX_PE10_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_24                            PE10
#define MX_PE10_GPIO_Pin                        GPIO_PIN_10
#define MX_PE10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PE13 */
#define MX_PE13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE13_Pin                             PE13
#define MX_PE13_GPIOx                           GPIOE
#define MX_PE13_PinState                        GPIO_PIN_SET
#define MX_PE13_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_20                            PE13
#define MX_PE13_GPIO_Pin                        GPIO_PIN_13
#define MX_PE13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PG11 */
#define MX_PG11_Pin                             PG11
#define MX_PG11_GPIOx                           GPIOG
#define MX_PG11_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_1                              PG11
#define MX_PG11_GPIO_Pin                        GPIO_PIN_11
#define MX_PG11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PE12 */
#define MX_PE12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE12_Pin                             PE12
#define MX_PE12_GPIOx                           GPIOE
#define MX_PE12_PinState                        GPIO_PIN_SET
#define MX_PE12_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_22                            PE12
#define MX_PE12_GPIO_Pin                        GPIO_PIN_12
#define MX_PE12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PG10 */
#define MX_PG10_Pin                             PG10
#define MX_PG10_GPIOx                           GPIOG
#define MX_PG10_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_5                              PG10
#define MX_PG10_GPIO_Pin                        GPIO_PIN_10
#define MX_PG10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF3 */
#define MX_PF3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF3_Pin                              PF3
#define MX_PF3_GPIOx                            GPIOF
#define MX_PF3_PinState                         GPIO_PIN_SET
#define MX_PF3_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED6                                 PF3
#define MX_PF3_GPIO_Pin                         GPIO_PIN_3
#define MX_PF3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PE15 */
#define MX_PE15_Pin                             PE15
#define MX_PE15_GPIOx                           GPIOE
#define MX_PE15_GPIO_PuPd                       GPIO_NOPULL
#define MX_POWEROFF_REMOTEIN                    PE15
#define MX_PE15_GPIO_Pin                        GPIO_PIN_15
#define MX_PE15_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PG13 */
#define MX_PG13_Pin                             PG13
#define MX_PG13_GPIOx                           GPIOG
#define MX_PG13_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_3                              PG13
#define MX_PG13_GPIO_Pin                        GPIO_PIN_13
#define MX_PG13_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF2 */
#define MX_PF2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF2_Pin                              PF2
#define MX_PF2_GPIOx                            GPIOF
#define MX_PF2_PinState                         GPIO_PIN_RESET
#define MX_PF2_GPIO_PuPd                        GPIO_NOPULL
#define MX_V24V_OUT4                            PF2
#define MX_PF2_GPIO_Pin                         GPIO_PIN_2
#define MX_PF2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE14 */
#define MX_PE14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE14_Pin                             PE14
#define MX_PE14_GPIOx                           GPIOE
#define MX_PE14_PinState                        GPIO_PIN_SET
#define MX_PE14_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_OUT_21                            PE14
#define MX_PE14_GPIO_Pin                        GPIO_PIN_14
#define MX_PE14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_OD

/* Pin PG12 */
#define MX_PG12_Pin                             PG12
#define MX_PG12_GPIOx                           GPIOG
#define MX_PG12_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_2                              PG12
#define MX_PG12_GPIO_Pin                        GPIO_PIN_12
#define MX_PG12_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PF5 */
#define MX_PF5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF5_Pin                              PF5
#define MX_PF5_GPIOx                            GPIOF
#define MX_PF5_PinState                         GPIO_PIN_SET
#define MX_PF5_GPIO_PuPd                        GPIO_NOPULL
#define MX_ET_RESETN                            PF5
#define MX_PF5_GPIO_Pin                         GPIO_PIN_5
#define MX_PF5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PB1 */
#define MX_PB1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_PinState                         GPIO_PIN_RESET
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_AI_IU_SW2                            PB1
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF4 */
#define MX_PF4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF4_Pin                              PF4
#define MX_PF4_GPIOx                            GPIOF
#define MX_PF4_PinState                         GPIO_PIN_SET
#define MX_PF4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PHY_RESET                            PF4
#define MX_PF4_GPIO_Pin                         GPIO_PIN_4
#define MX_PF4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_OD

/* Pin PG14 */
#define MX_PG14_Pin                             PG14
#define MX_PG14_GPIOx                           GPIOG
#define MX_PG14_GPIO_PuPd                       GPIO_NOPULL
#define MX_ST_IN_4                              PG14
#define MX_PG14_GPIO_Pin                        GPIO_PIN_14
#define MX_PG14_GPIO_Mode                       GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */

